aliases:
  - &restore-cache
    keys:
      - test-{{ .Branch }}-{{ checksum "package.json" }}
      - test-{{ .Branch }}

  - &save-cache
    key: test-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - ~/.cache/yarn
      - ~/react-native-detox-example/node_modules

  - &install-node-dependencies
    |
      yarn

defaults: &defaults
  working_directory: ~/react-native-detox-example

jobs:
  test-ios:
    <<: *defaults
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-node-dependencies
      - save_cache: *save-cache
      - run: npm run test:ios:release

  test-js:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-node-dependencies
      - save_cache: *save-cache
      - run: npm run test:unit

workflows:
  version: 2

  build:
    jobs:
      - test-js
      - test-ios

